name: Publish Package

on:
  release:
    types: [created]

jobs:
  npm-publish:
    name: Publish Package to npmjs.org
    runs-on: ubuntu-latest
    steps:
      # Check out project
      - uses: actions/checkout@v4
      # Install Node and dependencies
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: "https://registry.npmjs.org"
          cache: pnpm
      - run: corepack pnpm install
      # Build and publish
      - run: corepack pnpm build
      - run: npm publish --access public --scope @prgm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
